// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlrfleeflqqfacrknnzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1scmZsZWVmbHFxZmFjcmtubnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTMzMjcsImV4cCI6MjA2NzA4OTMyN30.w01nrhu491Q7eSK1TxjZopUwPwLZCIaCtqlg30VR0a0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});